### ISSUE TITLE
converter: swagger `collectionFormat` is ignored

### ISSUE THREAD

**Issue by pmstss** [NeuraLegion/har-sdk#129]
Input:
```
  /csvArrayParam:
    get:
      parameters:
        - name: p
          in: query
          collectionFormat: csv
          type: array
          minItems: 2
          items:
            type: string
```

Output:
```
    "queryString": [
      {
        "name": "p",
        "value": "lorem&lorem"
      }
    ],
    "url": "http://petstore.swagger.io/v1/csvArrayParam?lorem=&p=lorem"
```

Besides ignored comma-separated format, query string is not constructed correctly (`?lorem=&p=lorem`)
