### ISSUE TITLE
converter: oas path parameter `style` is ignored

### ISSUE THREAD

**Issue by pmstss** [NeuraLegion/har-sdk#131]
Input:
```
  /matrixStyleArrayParamExploded/{p}:
    get:
      parameters:
        - name: p
          in: path
          required: true
          style: matrix
          explode: true
          schema:
            type: array
            minItems: 2
            items:
              type: string
```
Output:
`"url": "http://petstore.swagger.io/v1/matrixStyleArrayParamExploded/lorem,lorem"`

Expected:
`"url": "http://petstore.swagger.io/v1/matrixStyleArrayParamExploded/;p=lorem;p=lorem"`
