### ISSUE TITLE
Inconsistency in precedence of default values between parser and converter for oas3 parameters

### ISSUE THREAD

**Issue by pmstss** [NeuraLegion/har-sdk#145]
There are multiple ways of providing default values via schema and that ways currently are not in sync between  `@har-sdk/editor` and  `@har-sdk/oas` in particular for oas3 parameters:

Case 1 - Value via `schema.example`:

```yaml
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      example: approved
```

Case 2 - Value via `schema.default`:

```yaml
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      default: approved
```

Case 3 - Value  via `parameter.example`:

```yaml
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
    example: approved
```

`TreeParser` from `@har-sdk/editor` supports cases 3 & 2  (with a 3 as top precedence, i. e. parsed tree will contain _that_ jsonPointer for value node),  while `oas2har` from `@har-sdk/oas` siupports 1 and 2. 

That's why a value set via `Editor.setParameterValue()` with a value jsonPointer from `TreeParser.parse()` does not present in generated har.

Need to be implemented:
- support case 1 in oas3 `TreeParser`
- support case 3 in `oas2har`
- align `editor` & `oas` precedence of that cases
